name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Memungkinkan deploy manual dari tab Actions di GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Konfigurasi Git untuk proses push
          git config --global user.email "deploy-action@github.com"
          git config --global user.name "GitHub Action"
          
          # Tambahkan Hugging Face Space sebagai remote git menggunakan token autentikasi
          # Ganti USERNAME dan SPACE_NAME di bawah ini sesuai dengan akun Anda!
          git remote add hf https://Faiz7557:$HF_TOKEN@huggingface.co/spaces/Faiz7557/safeschool-ai
          
          # Force push ke Hugging Face branch main
          git push --force hf main
